### ISSUE TITLE
Push recent updates

### ISSUE THREAD

**Issue by marcbachmann** [brandonhorst/node-mdfind#1]
Thanks for the module, but do you plan to commit it to github?
You published a non-working version to npm.
The last line in `mdfind()` contains `es.through(jsonify)`, which isn't working.
Please change

```
.pipe(_map$split$through.through(jsonify));
```

to

```
.pipe(_map$split$through.mapSync(jsonify));
```

**Comment by brandonhorst** [comment]
Sorry about that, should be fixed with https://github.com/brandonhorst/node-mdfind/commit/b6b4a63450fda2e99dc1b129e34fae738dd0d8df

I am actually moving away from this library for my own purposes, so if you plan to use it you may want to add some more tests.
