### ISSUE TITLE
No examples or documentation

### ISSUE THREAD

**Issue by cold-logic** [brandonhorst/node-mdfind#2]
@brandonhorst 

The README file could use some examples on how to use this. I had to dig around in the package.json file and the test folder to figure out how to use this. Some example spotlight queries would be a nice addition too.

**Comment by brandonhorst** [comment]
Added with 839ddc1904c36d506c8e6e694d9cec272ba60877

Note that this library isn't being actively maintained anymore, as I'm not using it for any projects. If you'd like to take over, we can arrange that.
